In [2]:
import numpy as np
import matplotlib.pyplot as plt

cadena = np.array([0, 0, 0, 1, 1, 3, 0, 3, 2, 1, 0])

In [3]:
def minimum_magnitude(cadena):
    dim = cadena.shape[0]
    nuevaCadena = np.zeros_like(cadena)
    for i in range(dim):
        if cadena[i] == 0:
            if cadena[i + 1] == 0:
                if cadena[i + 2] == 0 or cadena[i + 2] == 1:
                    print(i)
                    nuevaCadena[0 : dim - i] = cadena[i:]
                    nuevaCadena[dim - i :] = cadena[0:i]
                    break
    return nuevaCadena


nuevaCadena = minimum_magnitude(cadena)
print(nuevaCadena)

0
[0 0 0 1 1 3 0 3 2 1 0]


In [9]:
def first_difference(cadena, c):
    distance = np.zeros_like(cadena)
    if c == 4:
        # Distancia segun los numeros
        zero_dis =  [0,3,2,1]
        one_dis =   [1,0,3,2]
        two_dis =   [2,1,0,3]
        three_dis = [3,2,1,0]

        for i in range(cadena.shape[0]):
            if(i<cadena.shape[0]-1):
                if cadena[i+1] == 0:
                    distance[i] = zero_dis[cadena[i]]
                if cadena[i+1] == 1:
                    distance[i] = one_dis[cadena[i]]
                if cadena[i+1] == 2:
                    distance[i] = two_dis[cadena[i]]
                if cadena[i+1] == 3:
                    distance[i] = three_dis[cadena[i]]
            else:
                if cadena[0] == 0:
                    distance[i] = zero_dis[cadena[i]]
                if cadena[0] == 1:
                    distance[i] = one_dis[cadena[i]]
                if cadena[0] == 2:
                    distance[i] = two_dis[cadena[i]]
                if cadena[0] == 3:
                    distance[i] = three_dis[cadena[i]]
    if c == 8:
            # Distancia segun los numeros
            zero_dis =  [0,7,6,5,4,3,2,1]
            one_dis =   [1,0,7,6,5,4,3,2]
            two_dis =   [2,1,0,7,6,5,4,3]
            three_dis = [3,2,1,0,7,6,5,4]
            four_dis =  [4,3,2,1,0,7,6,5]
            five_dis =  [5,4,3,2,1,0,7,6]
            six_dis =   [6,5,4,3,2,1,0,7]
            seven_dis = [7,6,5,4,3,2,1,0]

            for i in range(cadena.shape[0]):
                if(i<cadena.shape[0]-1):
                    if cadena[i+1] == 0:
                        distance[i] = zero_dis[cadena[i]]
                    if cadena[i+1] == 1:
                        distance[i] = one_dis[cadena[i]]
                    if cadena[i+1] == 2:
                        distance[i] = two_dis[cadena[i]]
                    if cadena[i+1] == 3:
                        distance[i] = three_dis[cadena[i]]
                    if cadena[i+1] == 4:
                        distance[i] = four_dis[cadena[i]]
                    if cadena[i+1] == 5:
                        distance[i] = five_dis[cadena[i]]
                    if cadena[i+1] == 6:
                        distance[i] = six_dis[cadena[i]]
                    if cadena[i+1] == 7:
                        distance[i] = seven_dis[cadena[i]]
                else:
                    if cadena[0] == 0:
                        distance[i] = zero_dis[cadena[i]]
                    if cadena[0] == 1:
                        distance[i] = one_dis[cadena[i]]
                    if cadena[0] == 2:
                        distance[i] = two_dis[cadena[i]]
                    if cadena[0] == 3:
                        distance[i] = three_dis[cadena[i]]
                    if cadena[i] == 4:
                        distance[i] = four_dis[cadena[i]]
                    if cadena[i] == 5:
                        distance[i] = five_dis[cadena[i]]
                    if cadena[i] == 6:
                        distance[i] = six_dis[cadena[i]]
                    if cadena[i] == 7:
                        distance[i] = seven_dis[cadena[i]]
    return distance
print(cadena)
dis = first_difference(cadena, 4)
print(dis)


[0 0 0 1 1 3 0 3 2 1 0]
[0 0 1 0 2 1 3 3 3 3 0]
